export const DEPARTMENTS_LOADING = 'DEPARTMENTS_LOADING';
export const DEPARTMENTS_LOADED = 'DEPARTMENTS_LOADED';
export const DEPARTMENTS_ERROR = 'DEPARTMENTS_ERROR';
export const NEW_DEPARTMENT_LOADING = 'NEW_DEPARTMENT_LOADING';
export const NEW_DEPARTMENT_SUCCESS = 'NEW_DEPARTMENT_SUCCESS';
export const NEW_DEPARTMENT_FAIL = 'NEW_DEPARTMENT_FAIL';
export const RESET_DEPARTMENT_STATE = 'RESET_DEPARTMENT_STATE';
