// Dashboard
export const RESET_CATEGORIES_STATE = 'RESET_CATEGORIES_STATE';
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const CATEGORIES_LOADED = 'CATEGORIES_LOADED';
export const CATEGORIES_ERROR = 'CATEGORIES_ERROR';

// Display Items Page
export const RESET_DISPLAY_ITEMS_STATE = 'RESET_DISPLAY_ITEMS_STATE';
export const DISPLAY_ITEMS_LOADING = 'DISPLAY_ITEMS_LOADING';
export const DISPLAY_ITEMS_LOADED = 'DISPLAY_ITEMS_LOADED';
export const DISPLAY_ITEMS_ERROR = 'DISPLAY_ITEMS_ERROR';
