// Dashboard
export const RESET_CATEGORIES_STATE = 'RESET_CATEGORIES_STATE';
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const CATEGORIES_LOADED = 'CATEGORIES_LOADED';
export const CATEGORIES_ERROR = 'CATEGORIES_ERROR';
