// Dashboard
export const RESET_CATEGORIES_STATE = 'LAB_MANAGER_RESET_DASHBOARD_STATE';
export const CATEGORIES_LOADING = 'LAB_MANAGER_CATEGORIES_LOADING';
export const CATEGORIES_LOADED = 'LAB_MANAGER_CATEGORIES_LOADED';
export const CATEGORIES_ERROR = 'LAB_MANAGER_CATEGORIES_ERROR';
export const NEW_CAT_LOADING = 'LAB_MANAGER_NEW_CAT_LOADING';
export const NEW_CAT_SUCCESS = 'LAB_MANAGER_NEW_CAT_SUCCESS';
export const NEW_CAT_FAIL = 'LAB_MANAGER_NEW_CAT_FAIL';
export const EDIT_CAT_LOADING = 'LAB_MANAGER_EDIT_CAT_LOADING';
export const EDIT_CAT_SUCCESS = 'LAB_MANAGER_EDIT_CAT_SUCCESS';
export const EDIT_CAT_FAIL = 'LAB_MANAGER_EDIT_CAT_FAIL';
export const EDIT_CAT_RESET_STATE = 'LAB_MANAGER_EDIT_CAT_RESET_STATE';

// Display Items Page
export const RESET_DISPLAY_ITEMS_STATE =
  'LAB_MANAGER_RESET_DISPLAY_ITEMS_STATE';
export const DISPLAY_ITEMS_LOADING = 'LAB_MANAGER_DISPLAY_ITEMS_LOADING';
export const DISPLAY_ITEMS_LOADED = 'LAB_MANAGER_DISPLAY_ITEMS_LOADED';
export const DISPLAY_ITEMS_ERROR = 'LAB_MANAGER_DISPLAY_ITEMS_ERROR';
export const NEW_DSP_ITEM_LOADING = 'LAB_MANAGER_NEW_DSP_ITEM_LOADING';
export const NEW_DSP_ITEM_SUCCESS = 'LAB_MANAGER_NEW_DSP_ITEM_SUCCESS';
export const NEW_DSP_ITEM_FAIL = 'LAB_MANAGER_NEW_DSP_ITEM_FAIL';
export const EDIT_DSP_ITEM_LOADING = 'LAB_MANAGER_EDIT_DSP_ITEM_LOADING';
export const EDIT_DSP_ITEM_SUCCESS = 'LAB_MANAGER_EDIT_DSP_ITEM_SUCCESS';
export const EDIT_DSP_ITEM_FAIL = 'LAB_MANAGER_EDIT_DSP_ITEM_FAIL';
export const EDIT_DSP_ITEM_RESET_STATE =
  'LAB_MANAGER_EDIT_DSP_ITEM_RESET_STATE';

// Items Page
export const RESET_ITEMS_STATE = 'LAB_MANAGER_RESET_ITEMS_STATE';
export const RESET_NEW_ITEM_STATE = 'LAB_MANAGER_RESET_NEW_ITEM_STATE';
export const ITEMS_LOADING = 'LAB_MANAGER_ITEMS_LOADING';
export const ITEMS_LOADED = 'LAB_MANAGER_ITEMS_LOADED';
export const ITEMS_ERROR = 'LAB_MANAGER_ITEMS_ERROR';
export const NEW_ITEM_LOADING = 'LAB_MANAGER_NEW_ITEM_LOADING';
export const NEW_ITEM_SUCCESS = 'LAB_MANAGER_NEW_ITEM_SUCCESS';
export const NEW_ITEM_FAIL = 'LAB_MANAGER_EW_ITEM_FAIL';
export const ITEM_DELETE_LOADING = 'LAB_MANAGER_ITEM_DELETE_LOADING';
export const ITEM_DELETE_SUCCESS = 'LAB_MANAGER_ITEM_DELETE_SUCCESS';
export const ITEM_DELETE_FAIL = 'LAB_MANAGER_ITEM_DELETE_FAIL';
