// Dashboard
export const RESET_DASHBOARD_STATE = 'RESET_DASHBOARD_STATE';
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const CATEGORIES_LOADED = 'CATEGORIES_LOADED';
export const CATEGORIES_ERROR = 'CATEGORIES_ERROR';
export const NEW_CAT_LOADING = 'NEW_CAT_LOADING';
export const NEW_CAT_SUCCESS = 'NEW_CAT_SUCCESS';
export const NEW_CAT_FAIL = 'NEW_CAT_FAIL';
export const EDIT_CAT_LOADING = 'EDIT_CAT_LOADING';
export const EDIT_CAT_SUCCESS = 'EDIT_CAT_SUCCESS';
export const EDIT_CAT_FAIL = 'EDIT_CAT_FAIL';
export const EDIT_CAT_RESET_STATE = 'EDIT_CAT_RESET_STATE';

// Display Items Page
export const RESET_DISPLAY_ITEMS_STATE = 'RESET_DISPLAY_ITEMS_STATE';
export const DISPLAY_ITEMS_LOADING = 'DISPLAY_ITEMS_LOADING';
export const DISPLAY_ITEMS_LOADED = 'DISPLAY_ITEMS_LOADED';
export const DISPLAY_ITEMS_ERROR = 'DISPLAY_ITEMS_ERROR';
export const NEW_DSP_ITEM_LOADING = 'NEW_DSP_ITEM_LOADING';
export const NEW_DSP_ITEM_SUCCESS = 'NEW_DSP_ITEM_SUCCESS';
export const NEW_DSP_ITEM_FAIL = 'NEW_DSP_ITEM_FAIL';
export const EDIT_DSP_ITEM_LOADING = 'EDIT_DSP_ITEM_LOADING';
export const EDIT_DSP_ITEM_SUCCESS = 'EDIT_DSP_ITEM_SUCCESS';
export const EDIT_DSP_ITEM_FAIL = 'EDIT_DSP_ITEM_FAIL';
export const EDIT_DSP_ITEM_RESET_STATE = 'EDIT_DSP_ITEM_RESET_STATE';

// Items Page
export const RESET_ITEMS_STATE = 'RESET_ITEMS_STATE';
export const RESET_NEW_ITEM_STATE = 'RESET_NEW_ITEM_STATE';
export const ITEMS_LOADING = 'ITEMS_LOADING';
export const ITEMS_LOADED = 'ITEMS_LOADED';
export const ITEMS_ERROR = 'ITEMS_ERROR';
export const NEW_ITEM_LOADING = 'NEW_ITEM_LOADING';
export const NEW_ITEM_SUCCESS = 'NEW_ITEM_SUCCESS';
export const NEW_ITEM_FAIL = 'NEW_ITEM_FAIL';
export const ITEM_DELETE_LOADING = 'ITEM_DELETE_LOADING';
export const ITEM_DELETE_SUCCESS = 'ITEM_DELETE_SUCCESS';
export const ITEM_DELETE_FAIL = 'ITEM_DELETE_FAIL';
