// Dashboard
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const CATEGORIES_LOADED = 'CATEGORIES_LOADED';
export const CATEGORIES_ERROR = 'CATEGORIES_ERROR';
export const NEW_CAT_LOADING = 'NEW_CAT_LOADING';
export const NEW_CAT_SUCCESS = 'NEW_CAT_SUCCESS';
export const NEW_CAT_FAIL = 'NEW_CAT_FAIL';
