export const LABS_LOADING = 'LABS_LOADING';
export const LABS_LOADED = 'LABS_LOADED';
export const LABS_ERROR = 'LABS_ERROR';

export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const CATEGORIES_LOADED = 'CATEGORIES_LOADED';
export const CATEGORIES_ERROR = 'CATEGORIES_ERROR';

export const DISPLAY_ITEMS_LOADING = 'DISPLAY_ITEMS_LOADING';
export const DISPLAY_ITEMS_LOADED = 'DISPLAY_ITEMS_LOADED';
export const DISPLAY_ITEMS_ERROR = 'DISPLAY_ITEMS_ERROR';
