export const STUDENT_LABS_LOADING = 'STUDENT_LABS_LOADING';
export const STUDENT_LABS_LOADED = 'STUDENT_LABS_LOADED';
export const STUDENT_LABS_ERROR = 'STUDENT_LABS_ERROR';

export const CATEGORIES_LOADING = 'STUDENT_CATEGORIES_LOADING';
export const CATEGORIES_LOADED = 'STUDENT_CATEGORIES_LOADED';
export const CATEGORIES_ERROR = 'STUDENT_CATEGORIES_ERROR';

export const DISPLAY_ITEMS_LOADING = 'STUDENT_DISPLAY_ITEMS_LOADING';
export const DISPLAY_ITEMS_LOADED = 'STUDENT_DISPLAY_ITEMS_LOADED';
export const DISPLAY_ITEMS_ERROR = 'STUDENT_DISPLAY_ITEMS_ERROR';
